source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'Shimmer'
pod 'MDCSwipeToChoose'
pod 'DateTools'
xcodeproj '/Users/willdennis/dev/SCRecorder-master-echo/Examples/SCRecorderExamples.xcodeproj'